backend:
  name: git-gateway
  branch: master
media_folder: public/images/media #images that are uploaded via Netlify Cms interface will be stored in this folder
public_folder: /images/media
site_url: https://www.unafeminista.com
display_url: https://www.unafeminista.com
logo_url: /images/logo.png
locale: 'es'
local_backend: true
show_preview_links: false
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "blog" # The path to the folder where the markdown files are stored
    create: true # Allow users to create new markdown files.
    slug: "{{slug}}" # Filename template
    fields: # The fields for front matter. You will need to modify fields according to your project.
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string"}
      - {label: "Imagen de portada", name: "image", widget: "image"}
      - {label: "Etiqueta", name: "tag", widget: "select",multiple: true, options: ["Cultura","Salud","Notas Rebeldes","Recomendaciones"]}
      - {label: "Principal", name: "main", widget: "boolean", default: false}
      - {label: "Fecha", name: "date", widget: "string"}
      - {label: "Audio", name: "audio", widget: "string", required: false}
      - {label: "Autora", name: "author", widget: "string", default: "Anonima"}
      - {label: "Descripción Autora", name: "authorDescription", widget: "text", required: false}
      - {label: "Foto Autora", name: "authorPhoto", widget: "image"}
      - {label: "Instagram Autora", name: "authorTwitter", widget: "string", required: false}
      - {label: "Email Autora", name: "authorMail", widget: "string", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}
  - name: "directory"
    label: "Directorio"
    folder: "directory"
    create: true
    identifier_field: name
    slug: "{{day}}-{{month}}-{{year}}-{{name}}"
    fields:
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Profesión", name: "job", widget: "string"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Imagen", name: "image", widget: "image"}
      - {label: "Facebook", name: "facebook", widget: "string", required: false}
      - {label: "Instagram", name: "instagram", widget: "string", required: false}
      - {label: "Twitter", name: "twitter", widget: "string", required: false}
      - {label: "Linkedin", name: "linkedin", widget: "string", required: false}
      - {label: "Correo", name: "email", widget: "string", required: false}
      - {label: "Telefono", name: "phone", widget: "string", required: false}
      - {label: "Página web", name: "website", widget: "string", required: false}
  - name: "nosotras"
    label: "Nosotras"
    folder: "nosotras"
    create: true
    identifier_field: name
    slug: "{{name}}"
    fields:
      - {label: Nombre, name: name, widget: string}
      - {label: Posicion, name: position, widget: string}
      - {label: Descripcion, name: description, widget: text}
      - {label: Libro, name: book, widget: string}
      - {label: Mujer que admira, name: woman, widget: string}
      - {label: Pelicula, name: movie, widget: string}
      - {label: Frase favorita, name: quote, widget: string}
      - {label: Facebook, name: "facebook", widget: "string", required: false}
      - {label: Instagram, name: "instagram", widget: "string", required: false}
      - {label: Twitter, name: "twitter", widget: "string", required: false}
      - {label: Linkedin, name: "linkedin", widget: "string", required: false}
      - {label: Correo, name: "email", widget: "string", required: false}
      - {label: Foto, name: photo, widget: image}
  - name: "podcast"
    label: "Podcast"
    folder: "podcast"
    create: true
    identifier_field: id
    slug: "{{id}}"
    fields:
      - {label: Temporada x Capitulo (ej. 01x06), name: id, widget: string}
      - {label: Link, name: "link", widget: "string"}
      - {label: Portada, name: image, widget: image}
  - name: "pages"
    label: "Páginas"
    files:
      - label: "Libros"
        name: "books"
        file: "site/content/books.yml"
        fields:
          - label: "Libro actual"
            name: currentBook
            widget: object
            fields:
              - {label: Titulo, name: title, widget: string}
              - {label: Autora, name: author, widget: string}
              - {label: Portada, name: image, widget: image}
              - {label: Descripcion, name: description, widget: text}
          - {label: "Libro 1", name: book1, widget: image}
          - {label: "Libro 2", name: book2, widget: image}
          - {label: "Libro 3", name: book3, widget: image}
          - {label: "Libro 4", name: book4, widget: image}
